[features]
seeds = false
[programs.localnet]
cykura_staker = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 20000

[[test.genesis]]
address = "GokivDYuQXPZCWRkwMhdH2h91KpDQXBEmpgBgs55bnpH"
program = "./external-programs/smart_wallet.so"

[[test.genesis]]
address = "Govz1VyoyLD5BL6CSCxUJLVLsQHRwjfFj1prNsdNg5Jw"
program = "./external-programs/govern.so"

[[test.genesis]]
address = "LocktDzaV1W2Bm9DeZeiyz4J9zs4fRqNiYqQyracRXw"
program = "./external-programs/locked_voter.so"

[[test.genesis]]
address = "cysPXAjehMpVKUapzbMCCnpFxUFFryEWEaLgnb9NrR8"
program = "./external-programs/cyclos_core.so"
